version: '3'

services:
  flask:
    build: ./flask
    container_name: flask
    ports:
      - "8080:5000"


  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      - mongoServer
    environment:
      #- MONGO_URI=mongodb://root:pass@mongoServer:27017/scraping_db

  mongoServer:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo-server
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongoServer
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongoServer

networks:
  webscrapingV2:
    driver: bridge