version: '3'

services:
  flask:
    build: ./flask
    container_name: flask
    ports:
      - "8080:5000"
    networks:
      - webscrapingV2

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      - mysqlServer
    command: ["wait-for-it", "mysqlServer:3306", "--timeout=120", "--", "python", "spidersCrawling.py"]
    restart: on-failure
    networks:
      - webscrapingV2


  mysqlServer:
    image: mysql
    container_name: mysqlServer
    command: ["--init-file=/tmp/mysql-init.sql"]
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/db_dir:/var/lib/mysql
      - ./db/mysql-init.sql:/tmp/mysql-init.sql
    networks:
      - webscrapingV2
    ports:
      - "3307:3306"
    expose:
      - 3306

networks:
  webscrapingV2:
    driver: bridge